global:
  scrape_interval: 4s  # How often Prometheus scrapes targets

scrape_configs:
  # Scrape Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  # Scrape Loki metrics
  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]
