global:
  scrape_interval: 4s  # How often Prometheus scrapes targets

scrape_configs:
  - job_name: "prometheus"
    metrics_path: /metrics
    static_configs:
      - targets: ["10.154.102.45:8080"]
